### ISSUE TITLE
Meetups list updates

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#160]
Meetups list page has several problems:

* register/meetups/ -> should be just /meetups/, eg. create views.py in root directory and move the view from register name space. Also urls.py in root directory of the project should load the view.
* change order that latest meetup is displayed first.
* pagination is not styled (see events list how the pagination shoul looks like).
* meetup have to link to event details page of the meetup.

**Comment by neelab** [comment]
@ricco386 - I'll do this!

**Comment by neelab** [comment]
@ricco386 - Having some trouble setting up the project and running it locally. Is there a point of contact I can ask questions to?

**Comment by ricco386** [comment]
yes we have gitter: https://gitter.im/pyconsk/django-konfera event thou there is slovak chatter, you can ask the group in english and someone will respond...

**Comment by neelab** [comment]
Hi @ricco386 - Thanks! I'll ask you as well since it was a project setup question.
I added Konfera to my INSTALLED_APPS in `settings.py`:
```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'konfera'
]
```

And the url to `urls.py`:
```
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^konfera/', include('konfera.urls')),
]
```

But when I run `python manage.py loaddata konfera/fixtures/test_data.json`, I get an error of `CommandError: No fixture named 'test_data' found.`. I created a symbolic link according to the instructions, but I can't seem to get past this step when trying to run the app. Any ideas?

**Comment by ricco386** [comment]
@neelab I have updated documentation please have a look at [CONTRIBUTING.rst](https://github.com/pyconsk/django-konfera/blob/master/CONTRIBUTING.rst). Please try again with the updated steps, should work I went through the installation and seems ok now.
