### ISSUE TITLE
Refactor the schedule to be more automatic

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#291]
Current functionality of schedule is not working well. We can set talk and start and duration, but that does not make sense. We already know the duration from CfP, and honestly to fill this for the whole conference is not very user friendly. Besides if we want to amend it it would be terrible...

I am thinking how about we add order number to the talk, room and break time. This way we would be able re-order talks easily, current setup would require to move time for all the other talks.

Or suggest any other more user friendly way to order talks...

**Comment by mimmon** [comment]
I have already sent you a proposal with talks linked to a track so I will put it here to have a possibility to discuss it.
The main idea is that each talk has a number that will serve for ordering, it is not an index though. Talks are ordered by this number within a track. The number can be calculated automatically when talk is added to a track, but can also be explicitly set. The automatically added talk can receive a last number +10 (or +2 or +100), so there will be always, say, 9 possible slots in between, so that we can easily put another talk in between when reorganizing. This will also allow us to easily drop talk, because the rest will be automatically readjusted. There will be no empty slots in between unless we put there a specific time slots for a break.
I am not sure, however, if there is a way to easily edit certain fields in multiple records using list view in django admin - this would be very important feature if we want to easily organize it.

**Comment by ZoltanOnody** [comment]
> I am not sure, however, if there is a way to easily edit certain fields in multiple records using list view in django admin - this would be very important feature if we want to easily organize it.

There is. https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_changelist_form

**Comment by ricco386** [comment]
Closing. We are going to refactor #320
